/* Frecuencias */


.set REh, 851		@Nota Re agudo
.set DOhs, 902		@Nota Do sostenido agudo
.set SI, 1012		@Nota Si
.set LAs, 1072		@Nota La sostenido
.set LA, 1136		@Nota La
.set SOL, 1275		@Nota Sol
.set FAs, 1351		@Nota Fa sostenido
.set FA, 1432		@Nota Fa
.set MI, 1517		@Nota Mi
.set RE, 1703		@Nota Re
.set DOs, 1804		@Nota Do sostenido
.set SIg, 2025		@Nota Si grave
.set LAg, 2273		@Nota La grave
.set FAsg, 2703		@Nota Fa grave sostenido

.set SILENCIO, 5	@Es un ultrasonido, por lo que lo consideramos como un silencio


/* duraciones */
.set BLANCA, 1000000
.set NEGRAPUNTILLO, 750000
.set NEGRA, 500000
.set CORCHEAPUNTILLO, 375000
.set CORCHEA, 250000
.set SEMICORCHEA, 125000
.set SEMICORCHEACORTA, 120000
.set BLANCACORTA, 950000
.set SEPARANOTAS, 8000
